// gridview/src/App.vue
<script setup lang="ts">
import Tiles from "./components/Tiles.vue";
import { getQueryParam } from "./composables/getQueryParam.ts";

// URLパラメータから要素数、列数を取得。リアクティブな管理は不要なのでrefを使わない
const numTiles = getQueryParam("num_tiles", 10);
const columns = getQueryParam("num_columns", 4);
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <div style="width: 100vw; height: 400px; border: 1px solid black;">
    <Tiles :num_tiles="numTiles" :columns="columns" />
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// frontend/tiles/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import Tiles from "./components/Tiles";

import './App.css'

import { useQueryParam } from './hooks/useQueryParam.ts';

function App() {
  const [count, setCount] = useState(0)
  // URLパラメータから取得
  const numTiles = useQueryParam<number>("num_tiles", 15);
  const columns = useQueryParam<number>("num_columns", 4);

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
      <div style={{ width: "100vw", height: 400, border: "1px solid black" }}>
        <Tiles num_tiles={numTiles} columns={columns} />
      </div>
          </>
  )
}

export default App
